function [img_out,shape0_region_map, shape1_region_map] = ...
                    generate_img(window_size, pad_thickness, shrinkage_rate, shrinkage_base, orientation_randomize,...
                                shape0_density, shape1_density,...
                                shape0_force, shape1_force,...
                                shape0_img, shape1_img,...
                                shape0_scale, shape1_scale, ...
                                shape0_composition_img, shape1_composition_img,...
                                shape0_composition_scale, shape1_composition_scale, ...
                                shape1_scatter)

% shape 0 (TARGET) is drawn first

image = zeros(window_size,window_size);


if shape0_density>0
    % draw a binary mask that delineates the target region and the background
    [ ~, composition_mask ] = preprocess_and_makemask(shape0_composition_img, shape0_composition_scale, pad_thickness, shrinkage_rate, shrinkage_base);
    [ ~, shape0_region_map ] = draw( image, zeros(window_size,window_size), zeros(window_size,window_size),window_size, ...
                                      composition_mask, composition_mask, [],[], ...
                                      1,0,0,0,...
                                      orientation_randomize);

    % draw objects
    [ shape0_img, shape0_mask ] = preprocess_and_makemask(shape0_img, shape0_scale, pad_thickness, shrinkage_rate, shrinkage_base);
    [ image, mask ] = draw( image, zeros(window_size,window_size), shape0_region_map, window_size,  ...
                             [], [], shape0_img, shape0_mask,...
                             0, 0, shape0_density, shape0_force,...
                             orientation_randomize);
else
    mask = zeros(window_size,window_size);
end
if shape1_density>0
    [ ~, composition_mask ] = preprocess_and_makemask(shape1_composition_img, shape1_composition_scale, pad_thickness, shrinkage_rate, shrinkage_base);

    if shape1_scatter == 0
        [ ~, temp_region_map ] = draw( image, mask, shape0_region_map, window_size, ...
                                        composition_mask, composition_mask, [],[], ...
                                        1,0,0,0,...
                                        orientation_randomize);
        shape1_region_map = temp_region_map;
    else
        [ ~, temp_region_map ] = draw( image, zeros(window_size,window_size), zeros(window_size,window_size), window_size, ...
                                        composition_mask, composition_mask, [],[], ...
                                        1,0,0,0,...
                                        orientation_randomize);
        shape1_region_map = temp_region_map - mask;
        temp = zeros(window_size,window_size);
        while isempty(find(temp==1,1)) % find elements with value 1, up to 1 example
            % subplot(1,2,1);imagesc(temp);subplot(1,2,2);imagesc(shape0_region_map);pause()%%%%%%%%%%%%
            [ temp ] = shuffle( shape1_region_map,window_size,shape1_composition_scale );
            temp = temp.*(1-shape0_region_map);
        end
        shape1_region_map = temp;
    end
    
    [ shape1_img, shape1_mask ] = preprocess_and_makemask(shape1_img, shape1_scale, pad_thickness, shrinkage_rate, shrinkage_base);
    [ image, ~ ] = draw( image, mask, shape1_region_map, window_size,  ...
                          [], [], shape1_img, shape1_mask,...
                          0, 0, shape1_density, shape1_force,...
                          orientation_randomize);
else
    shape1_region_map = [];
end
img_out = image;
end
